=== evamnazara/DAM1-24-25-EON/src/ASIGNATURAS/LMAR/XMLSchema/tarefa 5/5a.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="edificio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="enderezo" type="tipoEnderezo"/>
                <xs:element name="dataConstrucion" type="tipoDataConstrucion"/>
                <xs:element name="material" type="xs:string" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="valor" type="tipoValor" use="optional"/>
            <xs:attribute name="alquiler" type="tipoAlquiler" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="tipoEnderezo">
        <xs:sequence>
            <xs:element name="rua" type="xs:string"/>
            <xs:element name="numero" type="tipoNumero"/>
            <xs:element name="poboacion" type="xs:string"/>
            <xs:element name="provincia" type="xs:string"/>
            <xs:element name="codigoPostal" type="tipoCP"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="tipoDataConstrucion">
        <xs:attribute name="mes" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="Xaneiro"/>
                    <xs:enumeration value="Febreiro"/>
                    <xs:enumeration value="Marzo"/>
                    <xs:enumeration value="Abril"/>
                    <xs:enumeration value="Maio"/>
                    <xs:enumeration value="XuÃ±o"/>
                    <xs:enumeration value="Xullo"/>
                    <xs:enumeration value="Agosto"/>
                    <xs:enumeration value="Setembro"/>
                    <xs:enumeration value="Outubro"/>
                    <xs:enumeration value="Novembro"/>
                    <xs:enumeration value="Decembro"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        
    </xs:complexType>
    
    <xs:simpleType name="tipoValor">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoAlquiler">
        <xs:restriction base="xs:string">
            <xs:enumeration value="verdadeiro"/>
            <xs:enumeration value="falso"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tipoNumero">
        <xs:restriction base="xs:unsignedShort">
            <xs:maxInclusive value="2000"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tipoCP">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{5}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tipoAno">
                <xs:restriction base="xs:int">
                    <xs:minInclusive value="1900"/>
                    <xs:maxInclusive value="3000"/>
                </xs:restriction>
            </xs:simpleType>
</xs:schema>

=== evamnazara/DAM1-24-25-EON/src/ASIGNATURAS/LMAR/XMLSchema/tarefa 5/5a.xml
<?xml version="1.0" encoding="UTF-8"?>
<edificio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="5a.xsd"
    
    alquiler="verdadeiro" 
    valor="410.50" >
   <enderezo>
      <rua>Ponzano</rua>
      <numero>66</numero>
      <poboacion>Madrid</poboacion>
      <provincia>Madrid</provincia>
      <codigoPostal>28003</codigoPostal>
   </enderezo>
   <dataConstrucion mes="Febreiro" ano="1989" />
   <material>formig√≥n</material>
</edificio>
