=== evamnazara/DAM1-24-25-EON/src/ASIGNATURAS/LMAR/XMLSchema/tarefa 5/5B.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="empresa">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="empregado" type="tipoEmpregado" maxOccurs="200"/>
            <xs:element name="departamento" type="tipoDepartamento"
           maxOccurs="8"/>
        </xs:sequence>
    </xs:complexType>
    <xs:key name="depUnico">
        <xs:selector xpath="departamento"/>
        <xs:field xpath="@codigo"/>
    </xs:key>
    
    <xs:keyref name="departamento" refer="depUnico">
        <xs:selector xpath="empregado"/>
        <xs:field xpath="departamento"/>
    </xs:keyref>
</xs:element>

 <xs:complexType name="tipoEmpregado">
    <xs:sequence>
        <xs:element name="nome" type="xs:string"/>
        <xs:element name="departamento" type="xs:string"/>
        <xs:element name="nss" type="tipoNSS"/> 
        <xs:element name="contactos" type="tipoContactos" nillable="true"/>
    </xs:sequence>
 </xs:complexType>
 
 <xs:simpleType name="tipoNSS">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{12}"/>
        </xs:restriction>
 </xs:simpleType>
 
 <xs:simpleType name="tipoContactos">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\d{9}\s)?(\d{9}\s)?(\d{9}\s)?(\d{9})?"/> 
        </xs:restriction>
 </xs:simpleType>

 <xs:complexType name="tipoDepartamento">
    <xs:sequence>
        <xs:element name="nome" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="codigo" type="xs:string" use="required"/>
 </xs:complexType>
</xs:schema>

=== evamnazara/DAM1-24-25-EON/src/ASIGNATURAS/LMAR/XMLSchema/UD4_T5_evamariaotero/5B.xml
<?xml version='1.0' encoding='UTF-8' ?>
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="5b.xsd">
    <empregado>
        <nome>Iria</nome>
        <departamento>IFC</departamento>
        <nss>123456789123</nss>
        <contactos xsi:nil="false">989898989 987654321 978787878 978787878</contactos>
    </empregado>
    
    <empregado>
        <nome>Xoel</nome>
        <departamento>CON</departamento>
        <nss>234567891234</nss>
        <contactos xsi:nil="true"></contactos>

    </empregado>
    
    <departamento codigo="IFC">
        <nome>Inform√°tica</nome>
    </departamento>
    
    <departamento codigo="CON">
        <nome>Contabilidade</nome>
    </departamento>
</empresa>
