<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ciclos [
  <!ELEMENT ciclos (ciclo+)>
    <!ELEMENT ciclo ((superior|medio)*, familia,codigo,nome) >
    
      <!ELEMENT superior (#PCDATA)>
      <!ELEMENT medio (#PCDATA)>
      <!ELEMENT familia (#PCDATA)>
      <!ELEMENT codigo (#PCDATA)>
      <!ELEMENT nome (#PCDATA)>
      

]>

<ciclos>
  <ciclo>
    <superior />
    <familia>Informática e comunicacións</familia>
    <codigo>CSIFC03</codigo>
    <nome>Desenvolvemento de aplicacións web</nome>
  </ciclo>
  <ciclo>
    <medio />
    <familia>Madeira, Moble e Cortiza</familia>
    <codigo>CMMMC01</codigo>
    <nome>Carpintaría e Moble</nome>
  </ciclo>
</ciclos>