=== evamnazara/DAM1-24-25-EON/src/ASIGNATURAS/LMAR/XML/tarea7/UD3_T7_tarefa7B_evaoteronazara.dtd
<!ELEMENT Informe (Descripción?, Seguro+, FechaInforme)>

<!ELEMENT Descripción (#PCDATA)>
<!ELEMENT FechaInforme EMPTY>
<!ELEMENT Seguro (Numero, (Cliente-Empresa | Cliente-Personal) )>
    <!ELEMENT Numero (#PCDATA)>
    <!ELEMENT Cliente-Personal (#PCDATA)>
    <!ELEMENT Cliente-Empresa (#PCDATA)>

<!ATTLIST Seguro tipo 
    (Edificio | Contenido) #REQUIRED>
    
<!ATTLIST FechaInforme 
    FechaInicio CDATA #REQUIRED 
    FechaFin CDATA #IMPLIED>

=== evamnazara/DAM1-24-25-EON/src/ASIGNATURAS/LMAR/XML/tarea7/UD3_T7_tarefa7B_evaoteronazara.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Informe SYSTEM "UD3_T7_tarefa7B_evaoteronazara.dtd">
<Informe>
    <!-- la descripcion es optativa -->
    <Descripción>Seguros </Descripción>
    <Seguro tipo="Edificio">
        <Numero>20</Numero>
        <Cliente-Personal>Eva María Otero </Cliente-Personal>
    </Seguro>

    <Seguro tipo="Contenido">
        <Numero>21</Numero>
        <Cliente-Empresa>IES Chan do Monte </Cliente-Empresa>
    </Seguro>

    <!-- fechafin es implied  -->
    <FechaInforme FechaInicio="14-02-2025" FechaFin="14-02-2026"/>
</Informe>
