<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edificio [
<!ELEMENT edificio (enderezo, dataConstrucion, material?) > 
    <!ELEMENT enderezo (rua, numero, poboacion, provincia, codigoPostal)>
    <!ELEMENT rua (#PCDATA)>
    <!ELEMENT numero (#PCDATA)>
    <!ELEMENT poboacion (#PCDATA)>
    <!ELEMENT provincia (#PCDATA)>
    <!ELEMENT codigoPostal (#PCDATA)>
    <!ELEMENT dataConstrucion EMPTY>
    <!ATTLIST dataConstrucion
          mes CDATA #REQUIRED
          ano CDATA #REQUIRED>
    <!ELEMENT material (#PCDATA)>
    <!ATTLIST edificio
          valor CDATA #IMPLIED
          alquiler (verdadeiro|falso) #REQUIRED>
]>
<!-- el atributo si es opcional no hay que ponerlo-->
  <edificio  alquiler="verdadeiro">
            <enderezo>
                    <rua>Ponzano</rua>
                    <numero>66</numero>
                    <poboacion></poboacion>
                    <provincia>Madrid</provincia>
                    <codigoPostal>28003</codigoPostal>
             </enderezo>  
              
            <dataConstrucion mes="febreiro" ano="1989"></dataConstrucion>
            
            <material>Formigón</material>
  </edificio>
 
